name: trademony
description: Trademony trading app
version: 1.0.0
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.10
  file_picker: ^5.2.3
  google_sign_in: ^6.1.0
  cupertino_icons: ^1.0.2
  path: ^1.8.2

flutter:
  uses-material-design: true
